---
- name: Send VM credentials email
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run email-sending Python script
      ansible.builtin.command: >
        python3 {{ playbook_dir }}/email_sender.py
      register: email_output

    - name: Show script output
      debug:
        var: email_output.stdout
