---
- hosts: esxi
  vars_files:
  - vars/main.yaml
#  vars_prompt:
#    - name: disksize
#      prompt: How big is the storage?
#      private: no

  tasks:
  - name: create VM
    community.vmware.vmware_guest:
     validate_certs: false
     hostname: "{{ esxi.hostname }}"
     username: "{{ esxi.username }}"
     password: "{{ esxi.password }}"
     datacenter: "{{ esxi.datacenter }}"
     folder: "/vm/"
     name: "{{ vmName }}"
     state: poweredoff
     guest_id: Ubuntu64Guest
     disk:
#     - size_gb: "{{ disksize }}"
     - size_gb: 5
       type: thin
       datastore: VMs
     hardware:
       memory_mb: 512
       num_cpus: 4
     networks:
     - name: VLAN30 - host VMs
       dns_servers: 10.0.1.50
       type: dhcp
     cdrom:
       - controller_number: 0
         unit_number: 0
         state: present 
         type: iso
         iso_path: "[VMs] Ubuntu Files/ubuntu-24.04.2-live-server-amd64.iso"
    delegate_to: localhost
    ignore_errors: true
