---
- name: Delete a Virtual Machine if it exists
  hosts: localhost
  gather_facts: no
  vars_files:
    - automation-frontend/vars.yaml

  tasks:

    - name: Check if VM exists
      community.vmware.vmware_guest_info:
        hostname: "{{ esxi.hostname }}"
        username: "{{ esxi.username }}"
        password: "{{ esxi.password }}"
        validate_certs: false
        name: "{{ vm_name }}"
        datacenter: "{{ esxi.datacenter }}"
      register: vm_info
      failed_when: false
      delegate_to: localhost

    - name: Fail if VM was not found
      ansible.builtin.fail:
        msg: "VM '{{ vm_name }}' not found. Cannot delete."
      when: vm_info.failed or vm_info.virtual_machines is not defined

    - name: Power off VM if it is running
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ esxi.hostname }}"
        username: "{{ esxi.username }}"
        password: "{{ esxi.password }}"
        validate_certs: false
        name: "{{ vm_name }}"
        state: poweredoff
        datacenter: "{{ esxi.datacenter }}"
      when: vm_info.virtual_machines[0].power_state == "poweredOn"
      delegate_to: localhost

    - name: Delete the VM
      community.vmware.vmware_guest:
        hostname: "{{ esxi.hostname }}"
        username: "{{ esxi.username }}"
        password: "{{ esxi.password }}"
        validate_certs: false
        name: "{{ vm_name }}"
        datacenter: "{{ esxi.datacenter }}"
        state: absent
      delegate_to: localhost

    - name: Confirm deletion
      debug:
        msg: "VM '{{ vm_name }}' has been deleted successfully."
