---
- name: Configure Fortinet Firewall Policy using SSH
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    firewall_host: "{{ hostvars['firewall']['ansible_host'] }}"
    firewall_user: "{{ hostvars['firewall']['ansible_user'] }}"
    firewall_password: "{{ hostvars['firewall']['ansible_password'] }}"

  tasks:
    - name: Read firewall configuration from JSON file
      ansible.builtin.slurp:
        src: "{{ playbook_dir }}/tmp/firewall_config.json"
      register: firewall_config

    - name: Parse JSON content into Ansible variables
      ansible.builtin.set_fact:
        config: "{{ firewall_config['content'] | b64decode | from_json }}"

    - name: Copy Python script to remote device
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/configure_firewall.py"
        dest: "{{ playbook_dir }}/tmp/firewall_config.json"
        mode: '0755'

    - name: Run Python script with variables from the JSON config
      ansible.builtin.command: >
        python3 {{ playbook_dir }}/tmp/configure_firewall.py
        --host {{ firewall_host }}
        --user {{ firewall_user }}
        --password {{ firewall_password }}
        --policy_id {{ config.policy_id }}
        --src_intf {{ config.src_intf }}
        --dst_intf {{ config.dst_intf }}
        --src_addr {{ config.src_addr }}
        --dst_addr {{ config.dst_addr }}
        --service {{ config.service }}
        --expiration {{config.schedule}}
      register: script_output

    - name: Show Python script output
      debug:
        var: script_output.stdout

