---
- name: Remove disabled firewall policies
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    firewall_host: "{{ hostvars['NSAT-Firewall']['ansible_host'] }}"
    firewall_user: "{{ hostvars['NSAT-Firewall']['ansible_user'] }}"
    firewall_password: "{{ hostvars['NSAT-Firewall']['ansible_password'] }}"
    ansible_python_interpreter: "/home/deploymentvm/Desktop/newenv/bin/python" 

  tasks:
    - name: Copy Python script to remote machine
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/remove_disabled_policies.py"
        dest: "{{ playbook_dir }}/remove_disabled_policies.py"
        mode: '0755'

    - name: Run Python script with firewall credentials
      ansible.builtin.command: >
        python3 {{ playbook_dir }}/remove_disabled_policies.py
        --host {{ firewall_host }}
        --user {{ firewall_user }}
        --password {{ firewall_password }}
      register: script_output

    - name: Show script output
      debug:
        var: script_output.stdout
