---
- name: Creating Virtual Machine
  hosts: esxi
  tasks:
    - name: Create Virtual Machine
      community.vmware.vmware_guest:
        hostname: "10.0.1.40"
        username: "root"
        password: "CNIT490sp25"
        validate_certs: no
        folder: "/vm"
        name: "TestVM"
        state: "poweredon"
        guest_id: "Linux"
        datastore: "VMs"
        hardware:
          memory_mb: 1024
          num_cpus: 1
        disk:
          - size_gb: 20
            type: "thin"
        networks:
          - name: "VM Network"
            type: "dhcp"
        cdrom:
          - type: "iso"
            iso_path: "[VMs] Ubuntu Files/ubuntu-24.04.2-live-server-amd64.iso"