---
- name: Installing Apache and deploying custom HTML file
  hosts: VM
  become: yes
  tasks:

    - name: Update apt package cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Copy custom HTML file to Apache web directory
      copy:
        src: /home/deploymentvm/Desktop/IaC-Automated-Network-Server-Deployment-for-Menards/Ansible-Playbooks/index.html
        dest: /var/www/html/index.html

    - name: Ensure that Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes
