---
- name: Installing Apache and deploying custom HTML file
  hosts: test #TODO need to get the IP address of the host that is being deployed.  it can be passed from the python script that is already getting that?
  become: yes
  tasks:

    - name: Update apt package cache
      shell: apt update -y && apt upgrade -y

    - name: install Apache
      command: apt install apache2 -y

    #- name: Fetch custom HTML file from remote server
    #  fetch:
    #    src: home/deploymentvm/Desktop/IaC-Automated-Network-Server-Deployment-for-Menards/Ansible-Playbooks  # Path on the remote machine
    #    dest: /tmp/index.html  # Temp location on the local Ansible control machine
    #    flat: yes  # Avoid creating directories

    - name: Copy custom HTML file to Apache web directory
      copy:
        src: /home/deploymentvm/Desktop/IaC-Automated-Network-Server-Deployment-for-Menards/Ansible-Playbooks/index.html  # Path to the fetched file
        dest: /var/www/html/index.html  # Destination path on the remote server

    - name: Ensure that Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

