---
- name: Creating DNS records
  hosts: winServer
  gather_facts: no
  become: yes
  tasks:
    - name: create new A records 
      community.windows.win_dns_record:
        name: "" #Name of Record
        type: "A"
        value: "" #Ip address
        zone: "" #Name of zone scope to manage