---
- name: Creating DNS records
  hosts: winServer
  gather_facts: no
  become: yes
  become_method: runas
  become_user: Administrator
  tasks:
    - name: create new A records 
      community.windows.win_dns_record:
        name: "TesstDELETE" #Name of Record
        type: "A"
        value: "100.100.100.100" #Ip address
        zone: "menards.local" #Name of zone scope to manage
