---
- hosts: esxi
  vars_files:
    - /home/deploymentvm/Desktop/Automation_frontend/IaC-Automated-Network-Server-Deployment-for-Menards/automation-frontend/vars.yaml
  become: yes

  tasks:
    - name: Calculate duration (days) between now and expiration date
      set_fact:
        vm_lifetime_days: "{{ ((expiration | to_datetime('%Y-%m-%d')) - (ansible_date_time.date | to_datetime('%Y-%m-%d'))).days }}"

    - name: Create VM based on form input
      community.vmware.vmware_guest:
        hostname: "10.0.1.40"
        username: "root"
        password: "CNIT490sp25"
        validate_certs: false
        datacenter: "ha-datacenter"
        folder: "/vm/"
        name: "{{ vm_name }}"
        state: poweredoff
        guest_id: "{{ 'windows9Server64Guest' if os == 'Windows' else 'Ubuntu64Guest' }}"
        disk:
          - size_gb: "{{ storage | default(20) | int }}"
            type: thin
            datastore: VMs
        hardware:
          memory_mb: "{{ (memory | default(2) | int) * 1024 }}"
          num_cpus: "{{ cpu | default(1) | int }}"
        networks:
          - name: VLAN30 - host VMs
            dns_servers: 10.0.1.50
            type: dhcp
        cdrom:
          - controller_number: 0
            unit_number: 0
            state: present 
            type: iso
            iso_path: >-
              {{ '[VMs] ISOs/SERVER_EVAL_x64FRE_en-us.iso' if os == 'Windows' else '[VMs] Ubuntu Files/ubuntu-24.04.2-live-server-amd64.iso' }}
      delegate_to: localhost
      ignore_errors: true

    - name: Schedule VM deletion using calculated expiration days
      ansible.builtin.command:
        cmd: |
          echo "/usr/bin/ansible-playbook delete_vm.yml" | at now + {{ vm_lifetime_days }} days
