---
- name: Create DHCP scope and options
  hosts: winServer
  gather_facts: no
  become: yes
  become_method: runas
  vars_files:
    - /home/deploymentvm/Ansible-Playbooks/vars/pass.yaml
# Creates a DHCP scope with running shell commands. Should change name, starting/ending range with variables
  tasks:
    # This task creates a new DHCP scope using PowerShell.
    # Currently hardcoded — consider replacing "Test Scope", StartRange, EndRange, and SubnetMask with variables.
    - name: Create DHCP scope
      win_shell: Add-DhcpServerv4Scope -Name "Test Scope" -StartRange 192.168.100.1 -EndRange 192.168.100.45 -SubnetMask 255.255.255.0
      register: dhcp_scope_results
      vars:
        ansible_become_method: runas
        ansible_become_user: "Administrator"
        ansible_become_password: "{{ win.password }}"
      ignore_errors: yes # Avoid failing the playbook if the scope already exists or another error occurs
