---
- name: Delete a Virtual Machine if it exists
  hosts: localhost
  gather_facts: no
  vars_files:
    - /home/deploymentvm/Desktop/IaC-Automated-Network-Server-Deployment-for-Menards/automation-frontend/vars.yaml
    - /home/deploymentvm/Desktop/IaC-Automated-Network-Server-Deployment-for-Menards/Ansible-Playbooks/vars/pass.yaml

  tasks:
  
    - name: DEBUG - Show vm_name
      debug:
        var: vm_name
  
    - name: Show if vm_name is defined
      debug:
        msg: "vm_name is set to {{ vm_name | default('undefined') }}"

    - name: Check if VM exists
      community.vmware.vmware_guest_info:
        hostname: "10.0.1.40"
        username: "root"
        password: "{{ esxi.password }}"
        validate_certs: false
        name: "{{ vm_name }}"
        datacenter: "ha-datacenter"
      register: vm_info
      failed_when: false
      delegate_to: localhost
      
    - name: Dump vm_info output
      debug:
        var: vm_info

    - name: Fail if VM was not found
      ansible.builtin.fail:
        msg: "VM '{{ vm_name }}' not found. Cannot delete."
      when: vm_info is not defined or vm_info.failed is defined and vm_info.failed or vm_info.instance is not defined or vm_info.instance.hw_name != vm_name

    - name: Power off VM if it is running
      community.vmware.vmware_guest_powerstate:
        hostname: "10.0.1.40"
        username: "root"
        password: "{{ esxi.password }}"
        validate_certs: false
        name: "{{ vm_name }}"
        state: poweredoff
        datacenter: "ha-datacenter"
      when: vm_info.instance.hw_power_status == "poweredOn"
      delegate_to: localhost

    - name: Delete the VM
      community.vmware.vmware_guest:
        hostname: "10.0.1.40"
        username: "root"
        password: "{{ esxi.password }}"
        validate_certs: false
        name: "{{ vm_name }}"
        datacenter: "ha-datacenter"
        state: absent
      delegate_to: localhost

    - name: Confirm deletion
      debug:
        msg: "VM '{{ vm_name }}' has been deleted successfully."
