---
- name: Schedule VM deletion in 2 minutes (for testing)
  hosts: localhost
  tasks:
    - name: Schedule test deletion job
      ansible.builtin.shell: echo "/usr/bin/echo 'Hello from test playbook' > /tmp/delete_test.txt" | at now + 2 minutes
      delegate_to: localhost
      run_once: true
        
    - name: Confirm job was scheduled
      ansible.builtin.command: atq
      register: atq_output
      
    - name: Show output of atq
      debug:
        var: atq_output.stdout
         
