---
- hosts: esxi
  vars_files:
    - /home/deploymentvm/Desktop/Automation_frontend/IaC-Automated-Network-Server-Deployment-for-Menards/automation-frontend/vars.yaml
  become: false

  tasks:
    - name: Calculate duration (days) between now and expiration date
      set_fact:
        vm_lifetime_days: "{{ ((expiration | to_datetime('%Y-%m-%d')) - (ansible_date_time.date | to_datetime('%Y-%m-%d'))).days | default(1) }}"

    - name: Create VM based on form input
      community.vmware.vmware_vm_vm_django:
        hostname: "10.0.1.40"
        username: "root"
        password: "CNIT490sp25"
        validate_certs: false
        datacenter: "ha-datacenter"
        folder: "/vm/"
        name: "test"
        state: poweredon
        guest_id: "Ubuntu64Guest"
        disk:
          - size_gb: 10
            type: thin
            datastore: VMs
        hardware:
          memory_mb: 5
          num_cpus: 2
        cdrom: 
          - controller_number: 0
            unit_number: 0
            state: present
            type: iso
            iso_path: '[VMs] Ubuntu Files/ubuntu-24.04.2-live-server-amd64.iso'
            networks:
              - name: VLAN30 - host VMs
                type: dhcp
            customization:
              linux:
                host_name: test
                timezone: "America/Chicago"
                dns_servers: 10.0.1.50
                ip: 
                  type: dhcp
                root_password: "test"
            wait_for_ip_address: true